RDF_GENE_ID = 'RDF Gene ID'
MIR_SYMBOL = 'miR Symbol'
SAMPLE = 'Sample'
ENSEMBL_GENE = 'Ensembl Gene ID'
ENSEMBL_TRANSCRIPT = 'Ensembl Transcript ID'
ENTREZ_ID = 'Entrez ID'
REFSEQ_ID = 'RefSeq ID'
GENE_SYMBOL = 'Gene Symbol'
LOCATION = 'Genomic Location'
P_VALUE = 'P-value'
SCORE = 'Score'
TSS_DISTANCE = 'TSS Distance'
RELATIVE = 'Relative To Gene'
OVERLAPPING = 'Number Of Overlapping'
CENTROMERE = 'Centromere Telomere'


CLOSEST_ENTREZ_ID = 'Closest Entrez ID'
CLOSEST_REFSEQ_ID = 'Closest RefSeq ID'
CLOSEST_GENE_SYMBOL = f'Closest {GENE_SYMBOL}'
CLOSEST_TSS_DISTANCE = 'TSS Closest Distance'
CLOSEST_RELATIVE = 'Relative To Closest Gene'